default_config:

frontend:
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
    - /mj_dashboard/resources/card-mod_3.2.0.js
  themes: !include_dir_merge_named custom_components/mj_dashboard/.dev/themes/

logger:
  default: warning
  logs:
    custom_components.mj_dashboard: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
